version: "1"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: userDb
      MYSQL_ROOT_PASSWORD: salam
      MYSQL_PASSWORD: salam
    ports:
      - "3306:3306"
    networks:
      - spring-net

  user-app:
    container_name: user-app
    build:
      context: .
    networks:
      - spring-net
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/userDb
       SPRING_DATASOURCE_USERNAME: root
       SPRING_DATASOURCE_PASSWORD: salam
       SPRING_PROFILES_ACTIVE: docker


networks:
  default :
  spring-net:
    name : "spring-net"
    driver: bridge