version: "1"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: userDb
      MYSQL_ROOT_PASSWORD: salam
      MYSQL_PASSWORD: salam
    ports:
      - "3306:3306"
    networks:
      - spring-net

  user-app:
    container_name: user-app
    build: .
    networks:
      - spring-net
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db


networks:
  default:
  spring-net:
    driver: bridge